eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true  # corrected spelling: 'fetch-registry' instead of 'fetch-registery'
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
